repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
          '--profile',
          'black',
          '--rm',
          'from typing import Tuple',
          '--rm',
          'from typing import Set',
          '--rm',
          'from typing import Dict',
          '--rm',
          'from typing import List',
          '--rm',
          'from typing import Optional',
          '--rm',
          'from typing import Union'
        ]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--ignore=E203,F401,W503', '--max-line-length=104']
        exclude: ^(tests/|.venv/|venv/|venv.back/|.venv.back/|devscripts/|setup.py)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
        files: 'youtube_dl_gui'
