title: yt-dlg
google_analytics: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
exclude:
- venv
- .pytest_cache
- .tox
- build
- dist
- yt_dlg.egg-info
kramdown:
  syntax_highlighter: rouge
  input: GFM
