name: yt-dlg
summary: A cross platform front-end GUI of the popular youtube-dl written in wxPython.
website: https://yt-dlg.github.io/yt-dlg/
license: Unlicense
icon: youtube_dl_gui/data/icons/hicolor/256x256/apps/youtube-dl-gui.png
description: |
      Download your favorite videos from supported sites.
adopt-info: yt-dlg
grade: stable 
confinement: devmode  # use 'strict' 
base: core22
architectures:
  - build-on: amd64

apps:
  yt-dlg:
    command: bin/yt-dlg
    plugs: [home, network, network-bind, removable-media]

parts:
  yt-dlg:
    plugin: python
    source: https://github.com/oleksis/youtube-dl-gui.git
    source-tag: v1.8.4
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version \
      "$(git describe --long --tags --always --match=v*.*.* | sed 's/v//')"
    build-packages:
      - freeglut3
      - freeglut3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libnotify-dev
      - libsdl2-dev
      - libsm-dev
      - libtiff-dev
      - libwebkit2gtk-4.0-dev
      - libxtst-dev      
      - libssl-dev
      - libpulse-dev
      - pkg-config
      - python3.10
      - python3.10-dev
      - libpython3.10-dev
      - python3.10-venv
    stage-packages:
      - yt-dlp
      - libasound2
      - libasyncns0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libdecor-0-0
      - libdeflate0
      - libepoxy0
      - libflac8
      - freeglut3
      - libglu1-mesa
      - libfontconfig1
      - libfribidi0
      - libgbm1
      - libgdk-pixbuf-2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libjbig0
      - libjpeg-turbo8
      - libnotify4
      - libogg0
      - libopus0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre2-32-0
      - libpixman-1-0
      - libpulse0
      - libsdl2-2.0-0
      - libsm6
      - libsndfile1
      - libthai0
      - libtiff5
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libwebp7
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - libxxf86vm1
      - libatomic1
      - libdw1
      - libegl1
      - libenchant-2-2
      - libevdev2
      - libgl1
      - libglvnd0
      - libglx0
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgstreamer1.0-dev
      - libgudev-1.0-0
      - libharfbuzz-icu0
      - libhyphen0
      - libjavascriptcoregtk-4.0-18
      - libmanette-0.2-0
      - libopengl0
      - libopenjp2-7
      - liborc-0.4-0
      - libpsl5
      - libsecret-1-0
      - libsoup2.4-1
      - libunwind8
      - libwebkit2gtk-4.0-37
      - libwebpdemux2
      - libwoff1
      - libxslt1.1
    python-packages:
      - pypubsub == 4.0.3
      - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
    organize:
      usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/libpulsecommon-15.99.so: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulsecommon-15.99.so
