name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.5.0
    with:
      env: '["py38", "py39", "py310", "py311"]'
      os: windows-latest
