name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.4.0
    with:
      env: '["py37", "py38", "py39", "py310"]'
      os: windows-latest
